name: s5
description: Use the S5 Network in your Flutter and Dart apps
version: 0.2.0
repository: https://github.com/s5-dev/s5-dart

environment:
  sdk: ^3.2.6

dependencies:
  hive: ^2.2.3
  lib5: 
    git: https://github.com/s5-dev/lib5.git
  lib5_crypto_implementation_dart:
    git: https://github.com/lukehmcc/lib5_crypto_implementation_dart.git

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
